# Generated by Django 3.1.7 on 2021-03-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cognito_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
